updates

diff --git a/bkjs b/bkjs
--- a/bkjs
+++ b/bkjs
@@ -557,7 +557,7 @@ case "$ARG" in
   init-monit-system)
     $ECHO "set daemon 30 with start delay 60" > /etc/monit.d/system.conf
     $ECHO "check system localhost if loadavg(1min) > 5 for 10 cycles then exec \"$0 send-alert\"" >> /etc/monit.d/system.conf
-    $ECHO "check filesystem rootfs with path / if space usage > 90% for 3 times within 5 cycles then exec exec \"$0 send-alert\"" >> /etc/monit.d/system.conf
+    $ECHO "check filesystem rootfs with path / if space usage > 90% for 3 times within 5 cycles then exec \"$0 send-alert\"" >> /etc/monit.d/system.conf
     monit reload
     ;;
 
@@ -729,7 +729,7 @@ case "$ARG" in
     fi
     email=$(grep 'set alert' /etc/monit.d/*|tail -1|awk '{print $NF}')
     if [ "$email" != "" ]; then
-       $ECHO "From:$email\nTo:$email\nSubject: $msg" |sendmail $email
+       $ECHO "From:$email\nTo:$email\nSubject: $(echo "$msg")" |sendmail $email
     fi
     ;;
 
@@ -1022,7 +1022,7 @@ case "$ARG" in
        ;;
     esac
 
-    ver=$(get_arg -version 3.2.3)
+    ver=$(get_arg -version 3.2.4)
     curl -L -o redis.tgz http://download.redis.io/releases/redis-$ver.tar.gz
 
     mkdir -p redis $BKJS_HOME/etc
@@ -1154,6 +1154,12 @@ case "$ARG" in
     kill $(ps agx|grep DynamoDBLocal|grep -v grep|awk '{print $1}')
     ;;
 
+  reset-dynamodb)
+    $0 stop-dynamodb
+    rm -rf $BKJS_HOME/var/*_us-east-1.db
+    $0 run-dynamodb
+    ;;
+
   get-cassandra)
     [ "$(get_arg -force)" != "" -a "$CASSANDRA_PREFIX" != "" ] && rm -rf $CASSANDRA_PREFIX
     if [ ! -d $CASSANDRA_PREFIX ]; then
@@ -1191,10 +1197,10 @@ case "$ARG" in
     ;;
 
   get-elasticsearch)
-  [ "$(get_arg -force)" != "" -a "$ELASTICSEARCH_PREFIX" != "" ] && rm -rf $ELASTICSEARCH_PREFIX
+    [ "$(get_flag -force)" != "" -a "$ELASTICSEARCH_PREFIX" != "" ] && rm -rf $ELASTICSEARCH_PREFIX
     if [ ! -d $ELASTICSEARCH_PREFIX ]; then
         mkdir -p $ELASTICSEARCH_PREFIX
-        curl -L -o es.tgz https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.0/elasticsearch-2.4.0.tar.gz
+        curl -L -o es.tgz https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.1/elasticsearch-2.4.1.tar.gz
         tar -C $ELASTICSEARCH_PREFIX --strip-components=1 -xzf es.tgz
         rm -rf es.tgz
         cd $ELASTICSEARCH_PREFIX
@@ -1221,7 +1227,13 @@ case "$ARG" in
     ;;
 
   init-elasticsearch-service)
-    echo "check process java with pidfile \"$BKJS_HOME/var/elasticsearch.pid\" start program = \"$0 run-elasticsearch $@\" as uid $BKJS_USER and gid $BKJS_GROUP stop program = \"$0 stop-elasticsearch\"" > /etc/monit.d/elasticsearch.conf
+    echo "check process java with pidfile \"$BKJS_HOME/var/elasticsearch.pid\" start program = \"$0 run-elasticsearch $@\" as uid $BKJS_USER and gid $BKJS_GROUP stop program = \"$0 stop-elasticsearch\" if failed url http://127.0.0.1:9200/ with timeout 15 seconds for 2 cycles then restart" > /etc/monit.d/elasticsearch.conf
+    monit reload
+    ;;
+
+  init-monit-elasticsearch-health)
+    host=$(get_arg -host elasticsearch)
+    echo "check host elasticsearch-health with address $host if failed url http://$host:9200/_cluster/health and content = 'green' with timeout 60 seconds for 2 cycles then alert" > /etc/monit.d/elasticsearch-health.conf
     monit reload
     ;;
 
@@ -1255,7 +1267,14 @@ case "$ARG" in
     kill $(ps agx|grep org.elasticsearch|grep -v grep|awk '{print $1}')
     ;;
 
+  reset-elasticsearch)
+    $0 stop-elasticsearch
+    rm -rf $ELASTICSEARCH_DIR/nodes
+    $0 run-elasticsearch
+    ;;
+
   upgrade-elasticsearch)
+    [ "$PLATFORM" != "Linux" ] && echo "Supports only Linux" && exit 1
     curl -XPUT localhost:9200/_cluster/settings -d '{"transient":{"cluster.routing.allocation.enable": "none"}}'
     $0 stop-elasticsearch
     $0 get-elasticsearch -force
@@ -1614,6 +1633,7 @@ EOF
     echo "  get-dynamodb - install local DynamoDB server in $BKJS_PREFIX/dynamodb"
     echo "  run-dynamodb - run local DynamoDB server installed in $BKJS_PREFIX/dynamodb, data files in $BKJS_HOME/var"
     echo "  stop-dynamodb - stop local DynamoDB server"
+    echo "  reset-dynamodb - remove local DynamoDB database and restart the server"
     echo "  get-cassandra - download and install Cassandra server in $CASSANDRA_PREFIX"
     echo "  init-cassandra [-db DB] - download and initialize Cassandra, create initial keyspace, run the server"
     echo "  run-cassandra - run local Cassandra server installed in $CASSANDRA_PREFIX, data files in $CASSANDRA_DIR"
@@ -1623,6 +1643,7 @@ EOF
     echo "  init-elasticsearch-service [-memsize PERCENT] [-memmax SIZE] [-nodetype TYPE] - setup monit to keep elasticsearch service running"
     echo "  run-elasticsearch [-memsize PERCENT] [-memmax SIZE] [-nodetype TYPE] - run local ElasticSearch server installed in $BKJS_PREFIX/elasticsearch, -memmax is max heap size, -memsize is the percent of the total memory to use, -nodetype can be node,master,data,client"
     echo "  stop-elasticsearch - stop local ElasticSearch server"
+    echo "  reset-elasticsearch - remove local ElasticSearch database and restart the server"
     echo "  upgrade-elasticsearch - update with a new version and restart"
     echo "  init-mysql [-db DB] - setup MySQL server for development and create initial database, start the server"
     echo "  run-mysql - run local MySQL server installed in $MYSQL_DIR"
@@ -1661,7 +1682,7 @@ EOF
     echo "  -db-del-all -table TABLE name VALUE ... - delete all records from the table that match the search criteria, name value pairs must define a primary key for the table"
     echo "  -db-drop -table TABLE name [-nowait] - drop a table"
     echo "  -db-backup [-path PATH] [-tables LIST] [-skip LIST] - save tables into json files in the home or specified path"
-    echo "  -db-restore [-path PATH] [-tables LIST] [-skip LIST] [-mapping ID1,ID2...] [-drop] [-continue] - restore tables from json files located in the home or specified path"
+    echo "  -db-restore [-path PATH] [-tables LIST] [-skip LIST] [-mapping ID1,ID2...] [-drop] [-continue] [-progress N] [-op add|update|put] [-noexit] [-exitdelay MS] - restore tables from json files located in the home or specified path"
     echo "  -aws-s3-get -path PATH - retrieve a file from S3"
     echo "  -aws-s3-put -path PATH -file FILE - store a file to S3"
     echo "  -aws-show-amazon-images [-filter PATTERN] [-arch ARCH] [-rootdev ebs|instance-store|*] [-devtype gp2|io1|standard|*] - show Amazon Linux AMIs (use %2A instead of *)"
