updates

diff --git a/bkjs b/bkjs
--- a/bkjs
+++ b/bkjs
@@ -60,7 +60,7 @@ get_arg() {
   for ((i = 0;i < ${#ARGS[@]}; ++i)); do
     [ "$1" = "${ARGS[i]}" ] && echo "${ARGS[i+1]}" && return 0
   done
-  echo $2
+  echo "$2"
 }
 
 # Returns 1 if an argument exists
@@ -75,13 +75,13 @@ concat_arg() {
   _v=$(get_arg $1)
   [ "$_v" == "" ] && echo $2
   [ "$2" != "" ] && _v="$2 $_v"
-  echo $_v
+  echo "$_v"
 }
 
 # Return value of the named pair from the variable that holds all them
 get_value() {
   v=$(echo "$1"|awk -F= "{if(\$1==\"$2\" && \$2!=\"\") print \$2}")
-  echo ${v:-$3}
+  echo "${v:-$3}"
 }
 
 # Return config parameter value by name
@@ -131,7 +131,7 @@ export BKJS_GET_CONFIG="$0 run-shell -log none -db-get-config -format args $@"
 [ "$MYSQL_PREFIX" = "" ] && export MYSQL_PREFIX=/usr
 [ "$DYNAMODB_PREFIX" = "" ] && export DYNAMODB_PREFIX=$BKJS_PREFIX/dynamodb
 [ "$ELASTICSEARCH_PREFIX" = "" ] && export ELASTICSEARCH_PREFIX=$BKJS_PREFIX/elasticsearch
-[ "$ELASTICSEARCH_DIR" = "" ] && export ELASTICSEARCH_DIR=$BKJS_HOME/var/elasticsearch
+[ "$ELASTICSEARCH_DIR" = "" ] && export ELASTICSEARCH_DIR=$BKJS_HOME/var
 [ "$MONGO_DIR" = "" ] && export MONGO_DIR=$BKJS_HOME/var/mongo
 [ "$BKJS_IDLETIME" = "" ] && export BKJS_IDLETIME=900
 [ "$BKJS_UPTIME" = "" ] && export BKJS_UPTIME=43200
@@ -306,7 +306,7 @@ case "$ARG" in
     # Allow only pubkey auth
     if [ "$(grep -s '#Bkjs' /etc/ssh/sshd_config)" = "" ]; then
        echo "Configuring ssh..."
-       egrep -v '^(#Bkjs|PasswordAuth|GSSAPIAuth|MaxAuth|MaxSess|ClientAlive)' /etc/ssh/sshd_config > /tmp/sshd_config
+       egrep -v '^(#Bkjs|PasswordAuth|GSSAPIAuth|MaxAuth|MaxSess|ClientAlive|PermitRootLogin)' /etc/ssh/sshd_config > /tmp/sshd_config
        echo "" >> /tmp/sshd_config
        echo "#Bkjs config" >> /tmp/sshd_config
        echo "PasswordAuthentication no" >> /tmp/sshd_config
@@ -315,6 +315,7 @@ case "$ARG" in
        echo "MaxSessions 10" >> /tmp/sshd_config
        echo "ClientAliveInterval 15" >> /tmp/sshd_config
        echo "ClientAliveCountMax 5" >> /tmp/sshd_config
+       echo "PermitRootLogin no" >> /tmp/sshd_config
        mv /tmp/sshd_config /etc/ssh
        chmod 600 /etc/sshd_config
        service sshd restart
@@ -508,8 +509,23 @@ case "$ARG" in
     echo "Init service $SERVICE with $BKJS_PATH"
     ln -sf $BKJS_PATH /etc/init.d/$SERVICE
     chkconfig $SERVICE on
-    # Start if command is given
-    [ "$BKJS_ARGS" != "" ] && service $SERVICE $BKJS_ARGS
+    server=$(get_arg -server)
+    if [ "$server" != "" ]; then
+       echo "BKJS_SERVER=$server" > /tmp/profile
+       grep -vs BKJS_SERVER $BKJS_HOME/etc/profile >> /tmp/profile
+       mv /tmp/profile $BKJS_HOME/etc
+       chown $BKJS_USER $BKJS_HOME/etc/profile
+    fi
+    # Execute a command if given
+    cmd=$(get_arg -cmd)
+    [ "$cmd" != "" ] && service $SERVICE $cmd
+    ;;
+
+  stop-service)
+    [ "$BKJS_PATH" = "" ] && BKJS_PATH=$BKJS_BIN
+    SERVICE=$(basename $BKJS_PATH | awk -F. '{print $1}')
+    echo "Stopping service $SERVICE with $BKJS_PATH"
+    chkconfig $SERVICE off
     ;;
 
   init-monit-system)
@@ -525,19 +541,19 @@ case "$ARG" in
     ;;
 
   init-logwatcher)
-    cron=$(get_arg -cron "*/30 * * * *")
+    cron=$(get_arg -cron '*/30 * * * *')
     echo 'MAILTO=""' > /etc/cron.d/$BKJS-logwatcher
     echo "$cron $BKJS_USER $BKJS_BIN run-logwatcher" >> /etc/cron.d/$BKJS-logwatcher
     ;;
 
   init-backup)
-    cron=$(get_arg -cron "30 3 * * *")
+    cron=$(get_arg -cron '30 3 * * *')
     echo 'MAILTO=""' > /etc/cron.d/$BKJS-backup
     echo "$cron root $BKJS_BIN run-backup" >> /etc/cron.d/$BKJS-backup
     ;;
 
   init-sync)
-    cron=$(get_arg -cron "*/15 * * * *")
+    cron=$(get_arg -cron '*/15 * * * *')
     echo 'MAILTO=""' > /etc/cron.d/$BKJS-sync
     echo "$cron $BKJS_USER $BKJS_BIN run-sync" >> /etc/cron.d/$BKJS-sync
     ;;
@@ -611,6 +627,50 @@ case "$ARG" in
     fi
     ;;
 
+  init-sendmail)
+    get_config user -user
+    get_config host -host
+    get_config password -password
+    [ "$user" = "" -o "$password" = "" -o "$host" = "" ] && echo "-host,-user,-password must be provided" && exit
+    yum -y install sendmail-cf
+    echo "AuthInfo:$host \"U:root\" \"I:$user\" \"P:$password\" \"M:LOGIN\"" > /etc/mail/authinfo
+    if [[ $host =~ us-east ]]; then
+       echo "AuthInfo:ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com \"U:root\" \"I:$user\" \"P:$password\" \"M:LOGIN\"" >> /etc/mail/authinfo
+    fi
+    if [[ $host =~ us-west ]]; then
+       echo "AuthInfo:ses-smtp-us-west-2-prod-14896026.us-west-2.elb.amazonaws.com \"U:root\" \"I:$user\" \"P:$password\" \"M:LOGIN\"" >> /etc/mail/authinfo
+    fi
+    makemap hash /etc/mail/authinfo.db < /etc/mail/authinfo
+    if [ "$(grep -s "$host" /etc/mail/access)" = "" ]; then
+       echo "Connect:$host RELAY" >> /etc/mail/access
+       makemap hash /etc/mail/access.db < /etc/mail/access
+    fi
+    if [ "$(grep -s "ses-smtp" /etc/mail/access)" = "" ]; then
+       if [[ $host =~ us-east ]]; then
+          echo "Connect:ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com RELAY" >> /etc/mail/access
+       fi
+       if [[ $host =~ us-west ]]; then
+          echo "Connect:ses-smtp-us-west-2-prod-14896026.us-west-2.elb.amazonaws.com RELAY" >> /etc/mail/access
+       fi
+       makemap hash /etc/mail/access.db < /etc/mail/access
+    fi
+    file=/etc/mail/relay.mc
+    egrep -v '^MAILER' /etc/mail/sendmail.mc > $file
+    echo "define(\`SMART_HOST', \`$host')dnl" >> $file
+    echo "define(\`RELAY_MAILER_ARGS', \`TCP \$h 587')dnl" >> $file
+    echo "define(\`confAUTH_MECHANISMS', \`LOGIN PLAIN')dnl" >> $file
+    echo "FEATURE(\`authinfo', \`hash -o /etc/mail/authinfo.db')dnl" >> $file
+    get_config domain -domain
+    if [ "$domain" != "" ]; then
+       echo "MASQUERADE_AS(\`$domain')dnl" >> $file
+       echo "FEATURE(masquerade_envelope)dnl" >> $file
+       echo "FEATURE(masquerade_entire_domain)dnl" >> $file
+    fi
+    egrep '^MAILER' /etc/mail/sendmail.mc >> $file
+    m4 $file > /etc/mail/sendmail.cf
+    service sendmail restart
+    ;;
+
   send-alert)
     event=$(get_arg -event $MONIT_EVENT)
     descr=$(get_arg -descr $MONIT_DESCRIPTION)
@@ -634,9 +694,11 @@ case "$ARG" in
 
   run|run-master|run-monitor|run-watcher|run-shell|bkjs|bksh)
     [ -f /usr/lib/node_modules/$BKJS_MOD/lib/app.js ] && SCRIPT=/usr/lib/node_modules/$BKJS_MOD/lib/app.js
+    [ -f $NODE_PATH/$BKJS_MOD/lib/app.js ] && SCRIPT=$NODE_PATH/$BKJS_MOD/lib/app.js
     [ -f $BKJS_PREFIX/lib/node_modules/$BKJS_MOD/lib/app.js ] && SCRIPT=$BKJS_PREFIX/lib/node_modules/$BKJS_MOD/lib/app.js
     [ -f $BKJS_HOME/node_modules/$BKJS_MOD/lib/app.js ] && SCRIPT=$BKJS_HOME/node_modules/$BKJS_MOD/lib/app.js
     [ -f node_modules/$BKJS_MOD/lib/app.js ] && SCRIPT=node_modules/$BKJS_MOD/lib/app.js
+    [ -f lib/app.js ] && SCRIPT=lib/app.js
     [ -f $BKJS_HOME/app.js ] && SCRIPT=$BKJS_HOME/app.js
     [ -f app.js ] && SCRIPT=app.js
     [ -z $SCRIPT ] && echo "ERROR: Cannot find $BKJS module or app.js" && exit 1
@@ -1009,6 +1071,7 @@ case "$ARG" in
     ;;
 
   get-dynamodb)
+  [ "$(get_arg -force)" != "" -a "$DYNAMODB_PREFIX" != "" ] && rm -rf $DYNAMODB_PREFIX
     if [ ! -d $DYNAMODB_PREFIX ]; then
        mkdir -p $DYNAMODB_PREFIX
        curl -L -o ddb.tgz http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
@@ -1028,6 +1091,7 @@ case "$ARG" in
     ;;
 
   get-cassandra)
+    [ "$(get_arg -force)" != "" -a "$CASSANDRA_PREFIX" != "" ] && rm -rf $CASSANDRA_PREFIX
     if [ ! -d $CASSANDRA_PREFIX ]; then
         mkdir -p $CASSANDRA_PREFIX $CASSANDRA_DIR
         curl -OL http://downloads.datastax.com/community/dsc.tar.gz
@@ -1063,9 +1127,10 @@ case "$ARG" in
     ;;
 
   get-elasticsearch)
+  [ "$(get_arg -force)" != "" -a "$ELASTICSEARCH_PREFIX" != "" ] && rm -rf $ELASTICSEARCH_PREFIX
     if [ ! -d $ELASTICSEARCH_PREFIX ]; then
         mkdir -p $ELASTICSEARCH_PREFIX
-        curl -L -o es.tgz https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.2.0/elasticsearch-2.2.0.tar.gz
+        curl -L -o es.tgz https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.3.2/elasticsearch-2.3.2.tar.gz
         tar -C $ELASTICSEARCH_PREFIX --strip-components=1 -xzf es.tgz
         rm -rf es.tgz
         cd $ELASTICSEARCH_PREFIX
@@ -1074,9 +1139,9 @@ case "$ARG" in
         echo "script.inline: on" >> config/elasticsearch.yml
         echo "script.indexed: on" >> config/elasticsearch.yml
         if [ "$OS_TYPE" = "amazon" ]; then
-           echo "network.host: _ec2_" >> config/elasticsearch.yml
-           echo "discovery.type: ec2" >> config/elasticsearch.yml
-           bin/plugin install cloud-aws
+           echo 'network.host: ["_ec2_","_local_"]' >> config/elasticsearch.yml
+           echo 'discovery.type: ec2' >> config/elasticsearch.yml
+           bin/plugin install cloud-aws -b
         fi
     fi
     ;;
@@ -1097,7 +1162,7 @@ case "$ARG" in
   run-elasticsearch)
     # Percent from the total memory
     memsize=$(get_arg -memsize)
-    [ "$size" != "" ] && memmax="$(( ($(free -m|grep Mem:|awk '{print $2}') * $memsize) / 100 ))m"
+    [ "$memsize" != "" ] && memmax="$(( ($(free -m|grep Mem:|awk '{print $2}') * $memsize) / 100 ))m"
     memmax=$(get_arg -memmax $memmax)
     if [ "$memmax" != "" ]; then
        export ES_MAX_MEM=$memmax
@@ -1108,6 +1173,15 @@ case "$ARG" in
 
   stop-elasticsearch)
     kill $(ps agx|grep org.elasticsearch|grep -v grep|awk '{print $1}')
+    ;;
+
+  upgrade-elasticsearch)
+    curl -XPUT localhost:9200/_cluster/settings -d '{"transient":{"cluster.routing.allocation.enable": "none"}}'
+    $0 stop-elasticsearch
+    $0 get-elasticsearch -force
+    monit reload
+    sleep $(get_arg -sleep 30)
+    curl -XPUT localhost:9200/_cluster/settings -d '{"transient":{"cluster.routing.allocation.enable": "all"}}'
     ;;
 
   get-mongodb)
@@ -1145,9 +1219,25 @@ case "$ARG" in
     [ "$region" != "" ] && region="--region $region"
     name=$(get_arg -name)
     [ "$name" != "" ] && tags="Name=tag:Name,Values=${name}"
-    instances=$(aws ec2 describe-instances $region --filter "Name=instance-state-name,Values=running" $tags --query 'Reservations[*].Instances[*].[InstanceId,PrivateIpAddress,PublicIpAddress,Tags[?Key==`Name`]]' --output text|awk '{if($4=="None")print $0;else if($1=="Name")print $2;else printf "%s ",$0;}')
-    [ "$(get_flag -showip)" != "" ] && instances=$(echo "$instances"|awk '{print $2}')
-    echo "$instances"
+    instances=$(aws ec2 describe-instances $region --filter "Name=instance-state-name,Values=running" $tags --query 'Reservations[*].Instances[*].[InstanceId,PrivateIpAddress,PublicIpAddress,KeyName,Tags[?Key==`Name`]]' --output text|awk '{if($4=="None")print $0;else if($1=="Name")print $2;else printf "%s ",$0;}')
+    fmt=$(get_arg -fmt)
+    [ "$fmt" != "" ] && instances=$(echo "$instances"|awk "{print $(echo $fmt|sed -e 's/id/\$1/' -e 's/ip/\$2/' -e 's/host/\$3/' -e 's/key/\$4/' -e 's/name/\$5/')}")
+    if [ "$(get_flag -line)" != "" ]; then
+       echo "$instances" | tr '\n' ' '
+    else
+       echo "$instances"
+    fi
+    ;;
+
+  ec2-ssh)
+    name=$(get_arg -name)
+    [ "$name" = "" ] && echo "-name is required" && exit 1
+    user=$(get_arg -user ec2-user)
+    region=$(get_arg -region)
+    cmd=$($0 show-instances -region "$region" -name "$name"|awk "{printf \"ssh -i ~/.ssh/\%s.pem -l $user %s\n\",\$4,\$3}"|head -1)
+    [ "$cmd" = "" ] && exit 1
+    [ "$BKJS_DEBUG" != "" ] && echo $cmd
+    eval $cmd
     ;;
 
   show-help)
@@ -1269,7 +1359,7 @@ db.describeTables({
     test: {
         id: { primary: 1 },
         name: {},
-        mtime: { type: "bigint", now: 1 },
+        mtime: { type: "now" },
     },
     // Extend accounts table
     bk_account: {
@@ -1394,9 +1484,10 @@ EOF
     echo "  init-monit-bkjs - setup monit to keep $BKJS service running without using any other services and monitor"
     echo "  init-alerts - init alerts in the monit and other systems, use DB config for the specified app name"
     echo "  init-postfix - [-domain DOMAIN] install and configure postfix for the domain"
+    echo "  init-sendmail - [-domain DOMAIN] -host HOST -user USER -password PW - configure sendmail as relay to SES SMTP"
     echo "  init-dns - install and setup dnsmasq for local cahching DNS server"
     echo "  init-instancejob - configure a checker for temporary job instance"
-    echo "  init-service - create bkjs service to be run on server startup, i.e. makes symlink /etc/init.d/$BKJS after which regular 'service' command can be used to manage the $BKJS service"
+    echo "  init-service [-server NAME] - create bkjs service to be run on server startup, i.e. makes symlink /etc/init.d/$BKJS after which regular 'service' command can be used to manage the $BKJS service"
     echo "  init-sync - setup a cron job to run run-sync command every 5 minites to check for new software on the \$BKJS_SYNC server"
     echo "  init-packages - install required packges and updates"
     echo "  init-devel - install development packages for node and modules compiclation"
@@ -1439,6 +1530,7 @@ EOF
     echo "  init-elasticsearch-service [-memsize PERCENT] [-memmax SIZE] - setup monit to keep elasticsearch service running"
     echo "  run-elasticsearch [-memsize PERCENT] [-memmax SIZE] - run local ElasticSearch server installed in $BKJS_PREFIX/elasticsearch, -memmax is max heap size, -memsize is the percent of the total memory to use"
     echo "  stop-elasticsearch - stop local ElasticSearch server"
+    echo "  upgrade-elasticsearch - update with a new version and restart"
     echo "  init-mysql [-db DB] - setup MySQL server for development and create initial database, start the server"
     echo "  run-mysql - run local MySQL server installed in $MYSQL_DIR"
     echo "  stop-mysql - stop local MySQL server"
@@ -1450,7 +1542,8 @@ EOF
     echo "  install-bkjs - install the $BKJS_MOD from the github using npm, build dependencies are passed in -args"
     echo "  build-bkjs - clone and build the $BKJS_MOD from the git in the current dir with dependencies specified in -args"
     echo "  build-node - build node and install in $BKJS_PREFIX or in [-prefix PATH], on Linux init-devel should be called before this command to install devel packages"
-    echo "  show-instances [-ip] [-region region] [-name name] - show running instances in region, optional tag pattern can be used for filter, -showip will show only IP addresses of instances"
+    echo "  show-instances [-region region] [-name name] [-fmt fmt]- show running instances in region, optional tag pattern can be used for filter, FMT may contain: id,ip,host,key,name which will be replaced with actual values"
+    echo "  ec2-ssh -name name [-region region] - login using ssh to a host by tag name, key name will be used to specify a keypair from ~/.ssh/"
     echo "  show-help - show all backend command line and config parameters"
     echo ""
     echo "bksh commands:"
